FROM node:20-alpine3.19

ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}

WORKDIR /app
COPY package*.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
RUN npm install

EXPOSE 4000

CMD [ "npm", "run", "dev" ]